apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.producer.name }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.producer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.producer.name }}
    spec:
      containers:
      - name: {{ .Values.producer.name }}
        image: "{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
        ports:
        - containerPort: {{ .Values.producer.service.port }}
        env:
        - name: SPRING_KAFKA_SERVER
          value: "{{ .Values.kafka.host }}:{{ .Values.kafka.port }}"
