server:
  port: 9090
spring:
  application:
    name: consumer
  kafka:
    autostart: false
    server: ${SPRING_KAFKA_SERVER:localhost:9092}
    topic: mytopic
    group: group-1
    id: myListener
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer