server:
  port: 8080
spring:
  application:
    name: producer
  kafka:
    server: ${SPRING_KAFKA_SERVER:localhost:9092}
    topic: mytopic
    group: group-1
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: "info, health, shutdown"
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true